name: Check dist

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  verify-build: # make sure the checked in dist/ folder matches the output of a rebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected and actual dist/ directories
        run: bin/check-diff
